'use client';

import { Navigation } from '@shared/ui/navigation';
import ConfigProviders from './config/ConfigProviders';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import './globals.css';
import { PagePaddingLayout } from '@shared/ui/layout';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProviders>
          <div
            id="container"
            style={{
              display: 'flex',
              flexFlow: 'row nowrap',
            }}
          >
            <Navigation />
            <PagePaddingLayout>{children}</PagePaddingLayout>
          </div>
        </ConfigProviders>
      </body>
    </html>
  );
}
